<style type="text/css">
    table, td{
        font:100% Arial, Helvetica, sans-serif;
    }
    table{width:100%;border-collapse:collapse;margin:1em 0;}
    td{text-align:left;padding:.5em;border:1px solid #fff;}
    th{text-align:center;padding:.5em;border:1px solid #fff;}
    th{background:#328aa4 url(../images/tr_back.gif) repeat-x;color:#fff;}
    td{background:#e5f1f4;}

    /* tablecloth styles */

    tr.even td{background:#e5f1f4;}
    tr.odd td{background:#f8fbfc;}

    th.over, tr.even th.over, tr.odd th.over{background:#4a98af;}
    th.down, tr.even th.down, tr.odd th.down{background:#bce774;}
    th.selected, tr.even th.selected, tr.odd th.selected{}

    td.over, tr.even td.over, tr.odd td.over{background:#ecfbd4;}
    td.down, tr.even td.down, tr.odd td.down{background:#bce774;color:#fff;}
    td.selected, tr.even td.selected, tr.odd td.selected{background:#bce774;color:#555;}

    /* use this if you want to apply different styleing to empty table cells*/
    td.empty, tr.odd td.empty, tr.even td.empty{background:#fff;}

    #flashMessengerContainer {
        position: absolute;
        left: 50%;
    }

    #flashMessenger {
        position: relative;
        left: -50%;
        top: 25px;
        width: 300px;
        margin-left: auto;
        margin-right: auto;
        padding: 10px;
        text-align: center;
        background-color: #E5F1F4;
    }

    .fieldset-kiri {
        width: 150px;
        float: left;
        margin-bottom: 5px;
        clear: left;
        vertical-align: top;
    }

    .fieldset-kanan {
        margin-left: 150px;
        margin-bottom: 5px;
        vertical-align: top;
    }

    .fieldset-kanan:before {
        content: ': ';
        vertical-align: top;
    }

    .fieldset-empty:before {
        content: ' ';
    }

    .fieldset-button {
        margin-left: 157px;
        margin-bottom: 5px;
    }

    .required:after {
        content: ' *';
        color: red;
    }

    .error-head {
        color: red;
        font-weight: bold;
    }

    .error-container {
        color: red;
        margin-left: 7px;
    }

    nav.pagination {
        font-size: 12px;
        color: #474747;
        display: block;
        text-align: center;
    }

    nav.pagination ul {
        margin: 0;
        padding: 0;
        list-style: none;
    }

    nav.pagination ul li {
        display: inline-block;
    }

    nav.pagination ul li + li {
        margin-left: 3px;
    }

    nav.pagination ul li a {
        padding: 5px 15px 5px 15px;
        color: inherit;
        text-decoration: none;
        text-shadow: 0 1px 0 rgba(255,255,255,1);
        line-height: 1;
        background: #F7F7F7;
        background: -webkit-gradient(linear,left top,left bottom,from(#F7F7F7),to(#DEDEDE));
        background: -moz-linear-gradient(top,#F7F7F7,#DEDEDE);
        background: -webkit-linear-gradient(top,#F7F7F7,#DEDEDE);
        background: linear-gradient(top,#F7F7F7,#DEDEDE);
        border: #EDEDED solid 1px;
        -moz-border-radius: 5px;
        -webkit-border-radius: 5px;
        border-radius: 5px;
        -moz-box-shadow:
            0 1px 1px rgba(0,0,0,0.5),
            0 1px 0 rgba(255,255,255,1) inset;
        -webkit-box-shadow:
            0 1px 1px rgba(0,0,0,0.5),
            0 1px 0 rgba(255,255,255,1) inset;
        box-shadow:
            0 1px 1px rgba(0,0,0,0.5),
            0 1px 0 rgba(255,255,255,1) inset;
        display: block;
    }

    nav.pagination ul li a:active,
    nav.pagination ul li a.current {
        margin-top: 3px;
        -moz-box-shadow:
            0 1px 0 rgba(255,255,255,1),
            0 1px 1px rgba(0,0,0,0.3) inset;
        -webkit-box-shadow:
            0 1px 0 rgba(255,255,255,1),
            0 1px 1px rgba(0,0,0,0.3) inset;
        box-shadow:
            0 1px 0 rgba(255,255,255,1),
            0 1px 1px rgba(0,0,0,0.3) inset;
    }
</style>

<script src="./libs/jquery-1.9.1.min.js"></script>
<script src="./libs/jquery.js" type="text/javascript" charset="utf-8"></script>
<script src="./libs/ui.datepicker.js" type="text/javascript" charset="utf-8"></script>
<link rel="stylesheet" href="./styles/ui.datepicker.css" type="text/css" media="screen" title="core css file" charset="utf-8" />

<script type="text/javascript">
    var showFlash = function (message) {
        $('body').prepend('<div id="flashMessengerContainer" style="display:none"></div>');
        $('#flashMessengerContainer').html('<div id="flashMessenger">' + message + '</div>');
        $('#flashMessengerContainer').slideDown('fast');
        $('#flashMessengerContainer').click(function () {
             $('#flashMessengerContainer').toggle('highlight')
        });
    };
</script>

<?php $flashMessengerMessages = $this->flashMessenger->collectMessages(); ?>
<script type='text/javascript'>
<?php
    foreach ($flashMessengerMessages as $flashMessengerMessage) :
?>
    showFlash('<?php echo $flashMessengerMessage ?>');
<?php endforeach; ?>
</script>

<div id="boxy">
