<style type="text/css">
    table,
    td {
        font:100% Arial, Helvetica, sans-serif;
    }
    table {
        width:100%;
        border-collapse:collapse;
        margin:1em 0;
    }

    th {
        text-align:center;
        padding:.5em;
        border:1px solid #fff;
        background:#328aa4 url(../images/tr_back.gif) repeat-x;
        color:#fff;
    }

    td {
        text-align:left;
        padding:.5em;
        border:1px solid #fff;
        background:#e5f1f4;
    }

    /* tablecloth styles */
    tr.even td {
        background:#e5f1f4;
    }

    tr.odd td {
        background:#f8fbfc;
    }

    th.over,
    tr.even th.over,
    tr.odd th.over {
        background:#4a98af;
    }

    th.down,
    tr.even th.down,
    tr.odd th.down {
        background:#bce774;
    }

    th.selected,
    tr.even th.selected,
    tr.odd th.selected {
    }

    td.over,
    tr.even td.over,
    tr.odd td.over {
        background:#ecfbd4;
    }

    td.down,
    tr.even td.down,
    tr.odd td.down {
        background:#bce774;
        color:#fff;
    }

    td.selected,
    tr.even td.selected,
    tr.odd td.selected {
        background:#bce774;
        color:#555;
    }

    /* use this if you want to apply different styleing to empty table cells*/
    td.empty,
    tr.odd td.empty,
    tr.even td.empty {
        background:#fff;
    }

    #flashMessengerContainer {
        position: absolute;
        left: 50%;
    }

    #flashMessenger {
        position: relative;
        left: -50%;
        top: 25px;
        width: 300px;
        margin-left: auto;
        margin-right: auto;
        padding: 10px;
        text-align: center;
        background-color: #E5F1F4;
    }

    .fieldset-kiri {
        width: 150px;
        float: left;
        margin-bottom: 5px;
        clear: left;
        vertical-align: top;
    }

    .fieldset-kanan {
        margin-left: 150px;
        margin-bottom: 5px;
        vertical-align: top;
    }

    .fieldset-kanan:before {
        content: ': ';
        vertical-align: top;
    }

    .fieldset-empty:before {
        content: ' ';
    }

    .fieldset-button {
        margin-left: 157px;
        margin-bottom: 5px;
    }

    .required:after {
        content: ' *';
        color: red;
    }

    .error-head {
        color: red;
        font-weight: bold;
    }

    .error-container {
        color: red;
        margin-left: 7px;
    }

    nav.pagination {
        font-size: 12px;
        color: #474747;
        display: block;
        text-align: center;
    }

    nav.pagination ul {
        margin: 0;
        padding: 0;
        list-style: none;
    }

    nav.pagination ul li {
        display: inline-block;
    }

    nav.pagination ul li + li {
        margin-left: 3px;
    }

    nav.pagination ul li a {
        padding: 5px 15px 5px 15px;
        color: inherit;
        text-decoration: none;
        text-shadow: 0 1px 0 rgba(255,255,255,1);
        line-height: 1;
        background: #F7F7F7;
        background: -webkit-gradient(linear,left top,left bottom,from(#F7F7F7),to(#DEDEDE));
        background: -moz-linear-gradient(top,#F7F7F7,#DEDEDE);
        background: -webkit-linear-gradient(top,#F7F7F7,#DEDEDE);
        background: linear-gradient(top,#F7F7F7,#DEDEDE);
        border: #EDEDED solid 1px;
        -moz-border-radius: 5px;
        -webkit-border-radius: 5px;
        border-radius: 5px;
        -moz-box-shadow:
            0 1px 1px rgba(0,0,0,0.5),
            0 1px 0 rgba(255,255,255,1) inset;
        -webkit-box-shadow:
            0 1px 1px rgba(0,0,0,0.5),
            0 1px 0 rgba(255,255,255,1) inset;
        box-shadow:
            0 1px 1px rgba(0,0,0,0.5),
            0 1px 0 rgba(255,255,255,1) inset;
        display: block;
    }

    nav.pagination ul li a:active,
    nav.pagination ul li a.current {
        margin-top: 3px;
        -moz-box-shadow:
            0 1px 0 rgba(255,255,255,1),
            0 1px 1px rgba(0,0,0,0.3) inset;
        -webkit-box-shadow:
            0 1px 0 rgba(255,255,255,1),
            0 1px 1px rgba(0,0,0,0.3) inset;
        box-shadow:
            0 1px 0 rgba(255,255,255,1),
            0 1px 1px rgba(0,0,0,0.3) inset;
    }

    .grid {
        float: left;
        margin-right: 20px;
    }

    input:required:invalid,
    input:focus:invalid,
    textarea:required:invalid,
    textarea:focus:invalid {
        background-image: url("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMCAYAAABWdVznAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAT1JREFUeNpi/P//PwMpgImBRMACY/x7/uDX39sXt/67cMoDyOVgMjBjYFbV/8kkqcCBrIER5KS/967s+rmkXxzI5wJiRSBm/v8P7NTfHHFFl5mVdIzhGv4+u///x+xmuAlcdXPB9KeqeLgYd3bDU2ZpRRmwH4DOeAI07QXIRKipYPD35184/nn17CO4p/+cOfjl76+/X4GYAYThGn7/g+Mfh/ZZwjUA/aABpJVhpv6+dQUjZP78Z0YEK7OezS2gwltg64GmfTu6i+HL+mUMP34wgvGvL78ZOEysf8M1sGgZvQIqfA1SDAL8iUUMPIFRQLf+AmMQ4DQ0vYYSrL9vXDz2sq9LFsiX4dLRA0t8OX0SHKzi5bXf2HUMBVA0gN356N7p7xdOS3w5fAgcfNxWtn+BJi9gVVBOQfYPQIABABvRq3BwGT3OAAAAAElFTkSuQmCC");
        background-position: right;
        background-repeat: no-repeat;
        box-shadow: none;
    }

    input:required:valid,
    input:focus:valid,
    textarea:required:valid,
    textarea:focus:valid {
        background-image: url("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMCAYAAABWdVznAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAZZJREFUeNpi/P//PwMpgImBRMAy58QshrNPTzP8+vOLIUInisFQyYjhz98/DB9/fmT48/+35v7H+8KNhE2+WclZd+G0gZmJmYGThUNz1fUVMZtvbWT59eUXG9wGZIWMUPj993eJ5VeWxuy8veM/CzPL3yfvH/9H0QBSBDYZyOVm4mGYfn6q4cory5lYmFh+MrEwM/76/YsR7mk2ZjbWP///WP37/y8cqIDhx58fjvtu7XV6//ndT34G/v8FasUsDjKO/+A2PP3wpGLd+TVsfOz8XH6KAT+nHpokcu7h6d9q/BoMxToVbBYqlt9///+1GO4/WVdpXqY/zMqXn13/+vTjI9mj94/y//v9/3e9ZRObvYbDT0Y2xnm///x+wsfHB3GSGLf41jb3rv0O8nbcR66d+HPvxf2/+YZFTHaqjl8YWBnm/vv37yly5LL8+vuLgYuVa3uf/4T/Kd8SnSTZpb6FGUXwcvJxbAPKP2VkZESNOBDx8+9PBm4OwR1TwmYwcfzjsBUQFLjOxs52A2YyKysrXANAgAEA7buhysQuIREAAAAASUVORK5CYII=");
        background-position: right;
        background-repeat: no-repeat;
        box-shadow: none;
    }

    input,
    button {
        margin-bottom: 0 !important;
    }

    input {
        height: 19px !important;
        font-size: 12px !important;
        padding: 1px !important;
    }

    input[type=button],
    input[type=submit],
    input[type=reset],
    button {
        height: 26px !important;
        font-size: 12px !important;
        padding: 5px !important;
    }

    fieldset {
        margin-bottom: 5px !important;
    }

    legend {
        font-size: 12px !important;
    }
</style>
<link rel="stylesheet" href="./styles/jquery-ui-1.10.4.custom.min.css" type="text/css" media="screen" charset="utf-8" />
<link rel="stylesheet" href="./styles/ui.datepicker.css" type="text/css" media="screen" charset="utf-8" />

<script src="./libs/jquery-1.9.1.min.js"></script>
<script src="./libs/jquery-migrate-1.2.1.js" type="text/javascript"></script>
<script src="./libs/jquery-ui-1.10.4.custom.min.js" type="text/javascript"></script>
<script src="./libs/ui.datepicker.js" type="text/javascript" charset="utf-8"></script>

<script type="text/javascript">
    var showFlash = function (message) {
        $('body').prepend('<div id="flashMessengerContainer" style="display:none"></div>');
        $('#flashMessengerContainer').html('<div id="flashMessenger">' + message + '</div>');
        $('#flashMessengerContainer').slideDown('fast');
        $('#flashMessengerContainer').click(function () {
             $('#flashMessengerContainer').toggle('highlight')
        });
    };
</script>

<?php $flashMessengerMessages = $this->flashMessenger->collectMessages(); ?>
<script type='text/javascript'>
<?php
    foreach ($flashMessengerMessages as $flashMessengerMessage) :
?>
    showFlash('<?php echo $flashMessengerMessage ?>');
<?php endforeach; ?>
</script>

<div id="boxy">
